from __future__ import annotations

PALLET_LENGTH_MM = 1200
PALLET_WIDTH_MM = 800
PALLET_MAX_HEIGHT_MM = 1500

USE_GRIPPER_MARGIN = False
GRIPPER_MARGIN_MM = 10

SUPPORT_MIN_RATIO = 0.85

EP_SORT_MODE = "bottom_up"

DISCRETIZE_DIMS = True
DISCRETIZE_STEP_MM = 50

RANDOM_SEED = 42

BOX_COUNT = 20
BOX_MIN_DIM_MM = 100
BOX_MAX_DIM_MM = 600

USE_GA = True

GA_POP_SIZE = 100
GA_NGEN = 50
GA_CXPB = 0.7
GA_MUTPB = 0.2
GA_TOURN_SIZE = 3
GA_ORDER_MUTPB = 0.2
GA_ROT_MUTPB = 0.2
GA_SKIP_PENALTY = 3.0
GA_POOL_PROCESSES = 0
GA_VERBOSE = True

EXPORT_JSON = True
EXPORT_JSON_PATH = "placement.json"
EXPORT_HTML = True
EXPORT_HTML_PATH = "palletization.html"
VIS_FRAME_MS = 200
VIS_DROP_FRAMES = 6
VIS_FLOAT_Z_OFFSET_MM = 300
EXPORT_IMAGE = True
EXPORT_IMAGE_PATH = "pallet_views.png"
